-- Hospital Management System (Oracle)
-- Tables: users, doctors, appointments, payments

CREATE TABLE users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR2(100) NOT NULL,
  email VARCHAR2(120) UNIQUE NOT NULL,
  password_hash VARCHAR2(255) NOT NULL,
  phone VARCHAR2(15) NOT NULL,
  age NUMBER(3) NOT NULL,
  gender VARCHAR2(15) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE doctors (
  doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  specialty VARCHAR2(60) NOT NULL,
  image_url VARCHAR2(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE appointments (
  appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  doctor_id NUMBER NOT NULL,
  problem_description CLOB,
  appointment_date DATE NOT NULL,
  status VARCHAR2(20) DEFAULT 'PENDING',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_appointments_user FOREIGN KEY (user_id) REFERENCES users(user_id),
  CONSTRAINT fk_appointments_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id)
);

CREATE TABLE payments (
  payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id NUMBER NOT NULL,
  amount NUMBER(10,2) NOT NULL,
  method VARCHAR2(30) NOT NULL,
  payment_status VARCHAR2(20) DEFAULT 'SUCCESS',
  payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_payments_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(appointment_id)
);
